version: "3.8"

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - app_network
    ports:
      - "13579:9000"  # Exposes only the app on port 13579

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network
    ports:
      - "13579:80"  # Exposing only the frontend

  mysql:
    image: mysql:8.0
    container_name: livewire_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: assessment
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
